=== BulkSecurityGeneratorProjectV2/EasyinnovaSL__DPFManager/src/main/resources/implementationcheckers/ProfileChecker.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0">
    <xsd:element name="implementationCheckerObject" type="implementationCheckerObjectType"/>
    
    <xsd:complexType name="implementationCheckerObjectType">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:sequence>
                <xsd:element name="rules" type="rulesType" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="rulesType">
        <xsd:sequence>
            <xsd:element name="rule" type="ruleType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="description" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="ruleType">
        <xsd:sequence>
            <xsd:element name="assert" type="assertType"/>
            <xsd:element name="diagnostic" type="diagnosticType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="reference" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="context" type="xsd:string"/>
        <xsd:attribute name="level" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="assertType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="test" type="xsd:string"/>
                <xsd:attribute name="diagnostics" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="diagnosticType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="id" type="xsd:string"/>
                <xsd:attribute name="lang" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    
</xsd:schema>

=== BulkSecurityGeneratorProjectV2/EasyinnovaSL__DPFManager/src/main/resources/implementationcheckers/TIAProfileChecker.xml
<?xml version="1.0" encoding="UTF-8"?>
<implementationCheckerObject xmlns="http://www.dpfmanager.org/ProfileChecker"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.dpfmanager.org/ProfileChecker ProfileChecker.xsd">
    
    <title>Tiff Baseline Implementation Checker</title>
    <iso>TIFF Baseline 6</iso>
    <description>Tiff Revision 6.0 Final - June 3, 1992</description>
    <version>1.0.0</version>
    <author>Easy Innova</author>
    <date>2016-09-20</date>
    
    
    <rules>
        <description lang="en">header-check</description>
        
        <rule id="bl-h-1" context="tiffValidationObject" level="critical">
            <title lang="es"></title>
            <description lang="en">Tiff image containing a header</description>
            <reference>Section 2, page 13</reference>
            <assert test="{count(header)==1}" diagnostics="d1 d2">Header must exist and be unique</assert>
            <diagnostic id="d1" lang="en">Header must exist and be unique</diagnostic>
            <diagnostic id="d2" lang="es">Tiene que existir una Ãºnica cabecera</diagnostic>
            
        </rule>
        
        <rule id="bl-h-4" context="header" level="critical">
            <title lang="es"></title>
            <description lang="en">Magic number exists</description>
            <reference>Section 2, page 13</reference>
            <assert test="{magicNumber}" diagnostics="d1">Magic Number must be defined</assert>
            <diagnostic id="d1" lang="en">Header must exist and be unique</diagnostic>
        </rule>
        
        
    </rules>
</implementationCheckerObject>
